togglz:
  enabled: true
  features:
    LOTTERY:
      enabled: true
  features-file: file:./togglz.properties
  console:
    enabled: true
    path: /togglz-console
    secured: false
    use-management-port: false